name: evolvepro
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - pandas
  - numpy
  - openpyxl
  - scikit-learn
  - scikit-learn-extra
  - xgboost
  - matplotlib
  - seaborn
  - biopython
  - scipy
  - pytorch
  - pip
  - pip:
    - -e .